passwordProject/basicApp/urls.py
from django.urls import path
from . import views

app_name = 'basicApp'

urlpatterns = [
    path('registration/',views.registration,name='registration'),
    path('user_login',views.user_login,name='user_login'),
]

passwordProject/passwordProject/urls.py
from django.contrib import admin
from django.urls import path,include
from basicApp import views
urlpatterns = [
    path('',views.index,name='index'),
    path('logout/',views.user_logout,name='user_logout'),
    path('admin/', admin.site.urls),
    path('basicApp/',include('basicApp.urls')),
]

passwordProject/basicApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,)
    portfoliaSite = models.URLField(blank=True)
    profilePic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

passwordProject/basicApp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicApp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields =('profilePic','portfoliaSite')

passwordProject/basicApp/views.py
from django.shortcuts import render
from basicApp.forms import UserForm,UserProfileInfoForm

from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,'basicApp/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HtttpResponse("User is not active")
        else:
            return HtttpResponse("Invalid Login Details")

    else:
        return render(request,'basicApp/login.html')



def registration(request):
    registered = False

    if request.method == 'POST':
        userForm = UserForm(data = request.POST)
        profileForm = UserProfileInfoForm(data = request.POST)

        if userForm.is_valid() and profileForm.is_valid():
            user = userForm.save()
            user.set_password(user.password)
            user.save()

            profile = profileForm.save(commit=False)
            profile.user = user

            if 'profilePic' in request.FILES:
                profile.profilePic = request.FILES['profilePic']

            profile.save()

            registered = True

        else:
            print(userForm.errors,profileForm.errors)
    else:
        userForm = UserForm
        profileForm = UserProfileInfoForm

    return render(request,'basicApp/registration.html',{'userForm':userForm,'profileForm':profileForm,'registered':registered})

passwordProject/templates/basicApp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

      <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
          <ul class="nav navbar-nav">
            <li class="navbar-brand">
              <a href="{% url 'index' %}">Home</a>
            </li>
            <li class="navbar-link">
              <a href="{% url 'basicApp:registration'%}">Registration</a>
            </li>
            <li class="navbar-link">
              <a href="{% url 'admin:index' %}">Admin</a>
            </li>
            {% if user.is_authenticated %}
            <li class="navbar-link">
              <a href="{% url 'user_logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="navbar-link">
              <a href="{% url 'basicApp:user_login' %}">Login</a>
            </li>
            {% endif %}

          </ul>

        </div>
        </nav>
        <div class="container">
          {% block body_block %}
          {% endblock %}
        </div>

passwordProject/templates/basicApp/index.html
{% extends 'basicApp/base.html' %}
{% block body_block %}
 <h1>This is Index Page </h1>
 {% endblock %}

passwordProject/templates/basicApp/login.html
{% extends 'basicApp/base.html' %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Login Page</h1>
    <form  action="{% url 'basicApp:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username</label>
      <input type="text"  name="username" placeholder="Enter username">

      <label for="password">Password</label>
      <input type="password" name="password" >

      <input type="submit"  value="Login">

    </form>

  </div>

</div>

{% endblock %}

passwordProject/templates/basicApp/registration.html
{% extends 'basicApp/base.html' %}
{% block body_block %}

<div class="jumbotron">


{% if registered %}
<h1>Thank you for registration </h1>
{% else %}
<h1>Register here!</h1>
<h1>Fill out the form</h1>
<form enctype="multipart/form-data" method="post">
  {% csrf_token %}
  {{ userForm.as_p }}
  {{ profileForm.as_p}}
  <input type="submit" name="" value="Register">
</form>
</div>
{% endif %}
{% endblock %}